#date: 2023-05-11T16:53:12Z
#url: https://api.github.com/gists/0097cb5e730b758470ddc3ae9b278181
#owner: https://api.github.com/users/tranvanhiep

#!/usr/bin/env python3
# Valid file name: commit-msg
# Rename if you download it

import sys, re

message_file = sys.argv[1]

# Match commit message generated by git merge or git pull
merge_commit_regex = re.compile(r'^Merge (?:remote-tracking )?branch .+(?:of .+)?into .+$')

# Ticket ID which is between non-alphanumeric characters will match
# Example: JIRA-1 message, jira-1: message, [JIRA-1] feat: message, feat(jira-1): message, etc.
ticket_id_regex = re.compile(r'\b(JIRA|jira)-[0-9]+\b')

with open(message_file, 'r') as file:
  lines = file.readlines()
  message = ''
  number_of_ticket_id = 0

  # Loop each line in the commit message
  for line in lines:
    stripped_line = line.strip()

    if stripped_line and not stripped_line.startswith('#'):
      # Extract non-comment line from commit message
      message += line
      # Count number of ticket ID in non-comment line
      result = ticket_id_regex.findall(stripped_line)
      number_of_ticket_id += len(result)

  # Check if the commit message is a merge commit
  result = merge_commit_regex.search(message)

  # Do not validate merge commit
  if result:
    sys.exit(0)

  # If it is not a merge commit
  # Check if there is 1 ticket ID, then it is a valid commit message
  if number_of_ticket_id == 1:
    sys.exit(0)
  # Else it is an invalid commit message
  else:
    message = ''.join(lines)
    print('ERROR: expect 1 Jira ticket ID in commit message, but got %s ticket ID(s) in commit message:\n%s' % (number_of_ticket_id, message))
    sys.exit(1)
