#date: 2023-11-03T16:51:58Z
#url: https://api.github.com/gists/a4e44a47673e6bd8a7c27f7045535ed1
#owner: https://api.github.com/users/ToroData

from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between generated and original text
original_text = "Original text of the target."
generated_text = "Text generated by the model."
similarity_score = cosine_similarity(
    [original_text], [generated_text]
)[0][0]
