#date: 2022-03-18T16:47:52Z
#url: https://api.github.com/gists/b822555eb57013b37c704a9bd28d2cb0
#owner: https://api.github.com/users/mahi49

# from base image node
FROM node:8.11-slim

WORKDIR /usr/node
WORKDIR app

RUN pwd

# command executable and version
ENTRYPOINT ["node"]