//date: 2021-12-02T17:10:39Z
//url: https://api.github.com/gists/79b20b063c01f845e399c3a239994d8c
//owner: https://api.github.com/users/ryan-holcombe

// Code generated by "fmgen". DO NOT EDIT.
package sample

import "time"

// NewSample generated factory method for Sample
func NewSample(Name string, LastUpdated time.Time, Age *int64) *Sample {
    result := &Sample{
        Name:        Name,
        LastUpdated: LastUpdated,
    }
    if Age != nil {
        result.Age = *Age
    }
    return result
}

// NewSimple generated factory method for Simple
func NewSimple(Name string) *Simple {
    result := &Simple{
        Name: Name,
    }
    return result
}