#date: 2025-12-16T17:02:15Z
#url: https://api.github.com/gists/d34827d176cbc1f3fda111c605940d85
#owner: https://api.github.com/users/kennethleungty

user_input = "Book business trip to Singapore between 20 and 24 Sep 2025 for an AI conference"
response = agent.invoke({"messages": [HumanMessage(user_input)]})

# Show the to-do list generated by the planning agent
print(response["todos"])