#date: 2025-11-13T17:05:30Z
#url: https://api.github.com/gists/6d4a870ae575c2d47f9ebbcb837cfaf1
#owner: https://api.github.com/users/wallacekelly-da

#!/bin/bash

# This script was generated by Google Gemini
# and tested on macOS.

# Copyright (c) 2025, by Digital Asset
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

# A script to find and list dependencies for all .dar files,
# excluding a list of specified prefixes, and sorting the results.
#
# Usage: ./find_dar_deps.sh /path/to/your/dars

# --- Configuration ---
# List prefixes to exclude, separated by |
# The ^ character means "starts with".
#
# === CHANGE 1: Added ^ghc to the list ===
EXCLUDE_REGEX="^daml-prim|^daml-stdlib|^daml-lf|^ghc-"

# The jq filter.
# 1. Selects packages...
# 2. ...where the name does NOT match the regex...
# 3. ...and formats the output as "name-version".
JQ_FILTER=".packages.[] | select(.name | test(\"$EXCLUDE_REGEX\") | not) | \"\\(.name), \\(.version)\""


# --- Input Validation ---
if [ -z "$1" ]; then
    echo "Error: No folder provided."
    echo "Usage: $0 <path-to-folder>"
    exit 1
fi

DAR_FOLDER=$1

if [ ! -d "$DAR_FOLDER" ]; then
    echo "Error: Folder not found: $DAR_FOLDER"
    exit 1
fi

echo "🔍 Scanning for dependencies in: $DAR_FOLDER"
echo "   (Excluding prefixes: ${EXCLUDE_REGEX//^/})"
echo ""

# --- Main Loop ---
# Find, sort (-z for null-terminated), and read files into the array.
# -maxdepth 1 prevents it from searching subdirectories.
# This correctly handles filenames with spaces or other special characters.
dar_files=()
while IFS= read -r -d $'\0' file; do
    dar_files+=("$file")
done < <(find "$DAR_FOLDER" -maxdepth 1 -name "*.dar" -print0 | sort -z)

if [ ${#dar_files[@]} -eq 0 ]; then
    echo "No .dar files found."
    exit 0
fi

for file in "${dar_files[@]}"; do
    echo "--- $(basename "$file") ---"
    
    # Run the command with the filter
    # The -r flag gives raw string output
    #
    # === CHANGE 2: Piped output to `sort` ===
    dependencies=$(dpm damlc inspect-dar --json "$file" | jq -r "$JQ_FILTER" | sort)

    if [ -z "$dependencies" ]; then
        echo "No non-excluded dependencies found."
    else
        echo "$dependencies"
    fi
    
    echo ""
done