#date: 2026-01-19T17:06:37Z
#url: https://api.github.com/gists/8624fb4587a6d6073adc030c7ee308ee
#owner: https://api.github.com/users/sl0thentr0py

 ▐▛███▜▌   Claude Code v2.1.12                                                                                                                                                                                                          
▝▜█████▛▘  Opus 4.5 · API Usage Billing                                                                                                                                                                                                 
  ▘▘ ▝▝    ~/sentry/sdks/sentry-ruby                                                                                                                                                                                                    
                                                                                                                                                                                                                                        
> This is a research task, don't write any code.                                                                                                                                                                                        
  https://github.com/getsentry/sentry-ruby/issues/2808                                                                                                                                                                                  
                                                                                                                                                                                                                                        
  We want to compile a list of metrics we could autocollect in the ruby ecosystem (think Rails, Sidekiq) that would help developers gain insights into their applications.                                                              
  Research online and look at codebases of the frameworks to make the list.                                                                                                                                                             
                                                                                                                                                                                                                                        
⏺ I'll research this topic by looking at the GitHub issue and gathering information about metrics in the Ruby ecosystem.                                                                                                                
                                                                                                                                                                                                                                        
⏺ Web Search("Rails application metrics monitoring ActiveSupport instrumentation events 2024 2025")                                                                                                                                     
  ⎿  Did 1 search in 28s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Web Search("Ruby GC garbage collection metrics stats monitoring runtime")                                                                                                                                                             
  ⎿  Did 1 search in 28s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Web Search("Rails ActiveRecord connection pool metrics monitoring size checkout timeout")                                                                                                                                             
  ⎿  Did 1 search in 24s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Web Search("Ruby process memory metrics RSS ObjectSpace heap monitoring")                                                                                                                                                             
  ⎿  Did 1 search in 24s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Web Search("Solid Queue Rails 8 metrics instrumentation monitoring background jobs")                                                                                                                                                  
  ⎿  Did 1 search in 25s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Let me check what the sentry-ruby SDK currently collects for metrics and look at a few more specific areas.                                                                                                                           
                                                                                                                                                                                                                                        
⏺ Web Search("Redis connection pool metrics monitoring Ruby Rails")                                                                                                                                                                     
  ⎿  Did 1 search in 22s                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
⏺ Search(pattern: "sentry-rails/**/*subscriber*.rb")                                                                                                                                                                                    
  ⎿  Found 21 files (ctrl+o to expand)                                                                                                                                                                                                  
                                                                                                                                                                                                                                        
⏺ Read(sentry-rails/lib/sentry/rails/log_subscribers/active_job_subscriber.rb)                                                                                                                                                          
  ⎿  Read 164 lines                                                                                                                                                                                                                     
                                                                                                                                                                                                                                        
⏺ Now I have a comprehensive picture. Let me compile the research findings into a structured list of metrics that could be auto-collected in the Ruby ecosystem.                                                                        
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  Auto-Collected Metrics for Ruby Ecosystem                                                                                                                                                                                             
                                                                                                                                                                                                                                        
  Based on my research, here's a comprehensive list of lightweight metrics that could be automatically collected in the Ruby ecosystem without duplicating tracing functionality. These metrics provide quick insights into application 
  and runtime health.                                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  1. Ruby Runtime Metrics                                                                                                                                                                                                               
                                                                                                                                                                                                                                        
  These are process-level metrics available in any Ruby application.                                                                                                                                                                    
  ┌───────────────────────────┬─────────┬──────────────────────────────────────┬───────────────────────────────────────────┐                                                                                                            
  │          Metric           │  Type   │                Source                │                Description                │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.gc.count             │ counter │ GC.count                             │ Total garbage collections (minor + major) │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.gc.minor_count       │ counter │ GC.stat[:minor_gc_count]             │ Minor GC runs (young objects only)        │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.gc.major_count       │ counter │ GC.stat[:major_gc_count]             │ Major GC runs (all objects)               │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.gc.total_time        │ gauge   │ GC.total_time (Ruby 3.1+)            │ Total GC time in nanoseconds              │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.heap.live_slots      │ gauge   │ GC.stat[:heap_live_slots]            │ Number of live object slots               │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.heap.free_slots      │ gauge   │ GC.stat[:heap_free_slots]            │ Available heap slots                      │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.heap.allocated_pages │ gauge   │ GC.stat[:heap_allocated_pages]       │ Total heap pages allocated                │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.memory.rss           │ gauge   │ /proc/self/status or get_process_mem │ Process RSS in bytes                      │                                                                                                            
  ├───────────────────────────┼─────────┼──────────────────────────────────────┼───────────────────────────────────────────┤                                                                                                            
  │ ruby.objects.count        │ gauge   │ ObjectSpace.count_objects            │ Live objects by type                      │                                                                                                            
  └───────────────────────────┴─────────┴──────────────────────────────────────┴───────────────────────────────────────────┘                                                                                                            
  Sources: https://www.speedshop.co/2017/03/09/a-guide-to-gc-stat.html, https://docs.ruby-lang.org/en/master/GC.html, https://docs.datadoghq.com/tracing/metrics/runtime_metrics/ruby/                                                  
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  2. Puma Web Server Metrics                                                                                                                                                                                                            
                                                                                                                                                                                                                                        
  For applications using Puma (the default Rails server).                                                                                                                                                                               
  ┌──────────────────────┬─────────┬────────────────────────┬─────────────────────────────────────────────┐                                                                                                                             
  │        Metric        │  Type   │         Source         │                 Description                 │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.workers.count   │ gauge   │ Puma stats             │ Number of worker processes (clustered mode) │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.threads.running │ gauge   │ stats[:running]        │ Spawned threads per worker                  │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.threads.busy    │ gauge   │ Calculated             │ Currently busy threads                      │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.threads.max     │ gauge   │ stats[:max_threads]    │ Maximum configured threads                  │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.pool_capacity   │ gauge   │ stats[:pool_capacity]  │ Available capacity for requests             │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.backlog         │ gauge   │ stats[:backlog]        │ Requests waiting for a thread               │                                                                                                                             
  ├──────────────────────┼─────────┼────────────────────────┼─────────────────────────────────────────────┤                                                                                                                             
  │ puma.requests.count  │ counter │ stats[:requests_count] │ Total requests served                       │                                                                                                                             
  └──────────────────────┴─────────┴────────────────────────┴─────────────────────────────────────────────┘                                                                                                                             
  Notes: The backlog metric is typically 0 since requests queue on the TCP socket. A high pool_capacity approaching 0 indicates capacity issues.                                                                                        
                                                                                                                                                                                                                                        
  Sources: https://puma.io/puma/file.stats.html, https://github.com/yabeda-rb/yabeda-puma-plugin, https://sosedoff.com/2023/01/10/puma-performance                                                                                      
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  3. ActiveRecord Connection Pool Metrics                                                                                                                                                                                               
                                                                                                                                                                                                                                        
  Database connection health indicators.                                                                                                                                                                                                
  ┌──────────────────────────┬───────┬─────────────────────────────┬────────────────────────────────┐                                                                                                                                   
  │          Metric          │ Type  │           Source            │          Description           │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.size             │ gauge │ connection_pool.stat[:size] │ Maximum pool size              │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.connections      │ gauge │ stat[:connections]          │ Currently open connections     │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.busy             │ gauge │ stat[:busy]                 │ Connections in use             │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.idle             │ gauge │ stat[:idle]                 │ Idle connections               │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.waiting          │ gauge │ stat[:waiting]              │ Threads waiting for connection │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.dead             │ gauge │ stat[:dead]                 │ Dead connections               │                                                                                                                                   
  ├──────────────────────────┼───────┼─────────────────────────────┼────────────────────────────────┤                                                                                                                                   
  │ db.pool.checkout_timeout │ gauge │ Config                      │ Checkout timeout in seconds    │                                                                                                                                   
  └──────────────────────────┴───────┴─────────────────────────────┴────────────────────────────────┘                                                                                                                                   
  Sources: https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html, https://devcenter.heroku.com/articles/concurrency-and-database-connections                                                          
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  4. Sidekiq Metrics                                                                                                                                                                                                                    
                                                                                                                                                                                                                                        
  For applications using Sidekiq for background jobs.                                                                                                                                                                                   
  ┌───────────────────────┬─────────┬───────────────────────────────┬──────────────────────────────────────────────┐                                                                                                                    
  │        Metric         │  Type   │            Source             │                 Description                  │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.processed     │ counter │ Sidekiq::Stats                │ Total jobs processed                         │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.failed        │ counter │ Stats                         │ Total jobs failed                            │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.enqueued      │ gauge   │ Stats                         │ Jobs currently enqueued                      │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.scheduled     │ gauge   │ Stats                         │ Scheduled jobs count                         │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.retries       │ gauge   │ Stats                         │ Jobs in retry queue                          │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.dead          │ gauge   │ Stats                         │ Jobs in dead queue                           │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.busy          │ gauge   │ Stats                         │ Currently executing jobs                     │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.workers       │ gauge   │ Stats                         │ Active worker processes                      │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.queue.size    │ gauge   │ Sidekiq::Queue.new(name).size │ Jobs per queue                               │                                                                                                                    
  ├───────────────────────┼─────────┼───────────────────────────────┼──────────────────────────────────────────────┤                                                                                                                    
  │ sidekiq.queue.latency │ gauge   │ queue.latency                 │ Queue latency in seconds (age of oldest job) │                                                                                                                    
  └───────────────────────┴─────────┴───────────────────────────────┴──────────────────────────────────────────────┘                                                                                                                    
  Sources: https://github.com/sidekiq/sidekiq/wiki/Monitoring, https://cronitor.io/guides/monitoring-sidekiq, https://www.datadoghq.com/blog/monitor-sidekiq-with-datadog/                                                              
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  5. Delayed::Job Metrics                                                                                                                                                                                                               
                                                                                                                                                                                                                                        
  For applications using Delayed Job.                                                                                                                                                                                                   
  ┌───────────────────────────┬──────────────┬─────────────────┬───────────────────────────────────┐                                                                                                                                    
  │          Metric           │     Type     │     Source      │            Description            │                                                                                                                                    
  ├───────────────────────────┼──────────────┼─────────────────┼───────────────────────────────────┤                                                                                                                                    
  │ delayed_job.enqueued      │ counter      │ Custom tracking │ Jobs enqueued                     │                                                                                                                                    
  ├───────────────────────────┼──────────────┼─────────────────┼───────────────────────────────────┤                                                                                                                                    
  │ delayed_job.failed        │ counter      │ Custom tracking │ Jobs failed                       │                                                                                                                                    
  ├───────────────────────────┼──────────────┼─────────────────┼───────────────────────────────────┤                                                                                                                                    
  │ delayed_job.waiting_count │ gauge        │ DB query        │ Jobs waiting for execution        │                                                                                                                                    
  ├───────────────────────────┼──────────────┼─────────────────┼───────────────────────────────────┤                                                                                                                                    
  │ delayed_job.queue_latency │ gauge        │ Oldest job age  │ Seconds since oldest job enqueued │                                                                                                                                    
  ├───────────────────────────┼──────────────┼─────────────────┼───────────────────────────────────┤                                                                                                                                    
  │ delayed_job.job_runtime   │ distribution │ Lifecycle hooks │ Job execution time                │                                                                                                                                    
  └───────────────────────────┴──────────────┴─────────────────┴───────────────────────────────────┘                                                                                                                                    
  Sources: https://github.com/dsalahutdinov/yabeda-delayed_job, https://docs.appsignal.com/ruby/integrations/delayed-job.html                                                                                                           
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  6. Solid Queue Metrics (Rails 8+)                                                                                                                                                                                                     
                                                                                                                                                                                                                                        
  For applications using Solid Queue (Rails 8 default).                                                                                                                                                                                 
  ┌─────────────────────────────┬───────┬──────────────────────────────────┬───────────────────────┐                                                                                                                                    
  │           Metric            │ Type  │              Source              │      Description      │                                                                                                                                    
  ├─────────────────────────────┼───────┼──────────────────────────────────┼───────────────────────┤                                                                                                                                    
  │ solid_queue.jobs.ready      │ gauge │ solid_queue_ready_executions     │ Jobs ready to execute │                                                                                                                                    
  ├─────────────────────────────┼───────┼──────────────────────────────────┼───────────────────────┤                                                                                                                                    
  │ solid_queue.jobs.scheduled  │ gauge │ solid_queue_scheduled_executions │ Scheduled jobs        │                                                                                                                                    
  ├─────────────────────────────┼───────┼──────────────────────────────────┼───────────────────────┤                                                                                                                                    
  │ solid_queue.jobs.claimed    │ gauge │ solid_queue_claimed_executions   │ Jobs being executed   │                                                                                                                                    
  ├─────────────────────────────┼───────┼──────────────────────────────────┼───────────────────────┤                                                                                                                                    
  │ solid_queue.jobs.failed     │ gauge │ solid_queue_failed_executions    │ Failed jobs           │                                                                                                                                    
  ├─────────────────────────────┼───────┼──────────────────────────────────┼───────────────────────┤                                                                                                                                    
  │ solid_queue.processes.alive │ gauge │ Heartbeat check                  │ Active processes      │                                                                                                                                    
  └─────────────────────────────┴───────┴──────────────────────────────────┴───────────────────────┘                                                                                                                                    
  Sources: https://github.com/rails/solid_queue, https://blog.appsignal.com/2025/06/18/a-deep-dive-into-solid-queue-for-ruby-on-rails.html                                                                                              
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  7. Resque Metrics                                                                                                                                                                                                                     
                                                                                                                                                                                                                                        
  For applications using Resque.                                                                                                                                                                                                        
  ┌───────────────────┬─────────┬─────────────────────────┬──────────────────────────────┐                                                                                                                                              
  │      Metric       │  Type   │         Source          │         Description          │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.processed  │ counter │ Resque.info[:processed] │ Total jobs processed         │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.failed     │ counter │ Resque::Failure.count   │ Total failed jobs            │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.pending    │ gauge   │ Resque.info[:pending]   │ Pending jobs across queues   │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.workers    │ gauge   │ Resque.workers.count    │ Active workers               │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.working    │ gauge   │ Resque.working.count    │ Workers currently processing │                                                                                                                                              
  ├───────────────────┼─────────┼─────────────────────────┼──────────────────────────────┤                                                                                                                                              
  │ resque.queue.size │ gauge   │ Resque.size(queue)      │ Jobs per queue               │                                                                                                                                              
  └───────────────────┴─────────┴─────────────────────────┴──────────────────────────────┘                                                                                                                                              
  Sources: https://github.com/resque/resque, https://github.com/quirkey/resque-metrics                                                                                                                                                  
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  8. Good Job Metrics                                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  For applications using GoodJob.                                                                                                                                                                                                       
  ┌─────────────────────────┬─────────┬────────────────┬─────────────────────────────┐                                                                                                                                                  
  │         Metric          │  Type   │     Source     │         Description         │                                                                                                                                                  
  ├─────────────────────────┼─────────┼────────────────┼─────────────────────────────┤                                                                                                                                                  
  │ good_job.jobs.queued    │ gauge   │ DB count       │ Jobs waiting to be executed │                                                                                                                                                  
  ├─────────────────────────┼─────────┼────────────────┼─────────────────────────────┤                                                                                                                                                  
  │ good_job.jobs.finished  │ counter │ DB count       │ Completed jobs              │                                                                                                                                                  
  ├─────────────────────────┼─────────┼────────────────┼─────────────────────────────┤                                                                                                                                                  
  │ good_job.jobs.discarded │ counter │ DB count       │ Discarded jobs              │                                                                                                                                                  
  ├─────────────────────────┼─────────┼────────────────┼─────────────────────────────┤                                                                                                                                                  
  │ good_job.queue_latency  │ gauge   │ Oldest job age │ Queue latency per queue     │                                                                                                                                                  
  └─────────────────────────┴─────────┴────────────────┴─────────────────────────────┘                                                                                                                                                  
  Sources: https://github.com/bensheldon/good_job, https://judoscale.com/blog/autoscale-good-job-queues                                                                                                                                 
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  9. Rails Cache Metrics                                                                                                                                                                                                                
                                                                                                                                                                                                                                        
  Cache hit/miss rates from ActiveSupport instrumentation.                                                                                                                                                                              
  ┌─────────────────┬─────────┬───────────────────────────────────────┬───────────────┐                                                                                                                                                 
  │     Metric      │  Type   │                Source                 │  Description  │                                                                                                                                                 
  ├─────────────────┼─────────┼───────────────────────────────────────┼───────────────┤                                                                                                                                                 
  │ cache.read.hit  │ counter │ cache_read.active_support (hit=true)  │ Cache hits    │                                                                                                                                                 
  ├─────────────────┼─────────┼───────────────────────────────────────┼───────────────┤                                                                                                                                                 
  │ cache.read.miss │ counter │ cache_read.active_support (hit=false) │ Cache misses  │                                                                                                                                                 
  ├─────────────────┼─────────┼───────────────────────────────────────┼───────────────┤                                                                                                                                                 
  │ cache.write     │ counter │ cache_write.active_support            │ Cache writes  │                                                                                                                                                 
  ├─────────────────┼─────────┼───────────────────────────────────────┼───────────────┤                                                                                                                                                 
  │ cache.delete    │ counter │ cache_delete.active_support           │ Cache deletes │                                                                                                                                                 
  └─────────────────┴─────────┴───────────────────────────────────────┴───────────────┘                                                                                                                                                 
  Sources: https://guides.rubyonrails.org/active_support_instrumentation.html                                                                                                                                                           
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  10. ActionCable / WebSocket Metrics                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  For applications using ActionCable.                                                                                                                                                                                                   
  ┌────────────────────────────┬─────────┬──────────────────────────────┬──────────────────────────────┐                                                                                                                                
  │           Metric           │  Type   │            Source            │         Description          │                                                                                                                                
  ├────────────────────────────┼─────────┼──────────────────────────────┼──────────────────────────────┤                                                                                                                                
  │ action_cable.connections   │ gauge   │ Custom tracking              │ Active WebSocket connections │                                                                                                                                
  ├────────────────────────────┼─────────┼──────────────────────────────┼──────────────────────────────┤                                                                                                                                
  │ action_cable.subscriptions │ gauge   │ Custom tracking              │ Active channel subscriptions │                                                                                                                                
  ├────────────────────────────┼─────────┼──────────────────────────────┼──────────────────────────────┤                                                                                                                                
  │ action_cable.broadcasts    │ counter │ broadcast.action_cable event │ Messages broadcast           │                                                                                                                                
  └────────────────────────────┴─────────┴──────────────────────────────┴──────────────────────────────┘                                                                                                                                
  Sources: https://stanko.io/monitoring-actioncable-GdeaeHfIU4Yk, https://evilmartians.com/chronicles/anycable-actioncable-on-steroids                                                                                                  
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  11. HTTP Client Metrics                                                                                                                                                                                                               
                                                                                                                                                                                                                                        
  For outgoing HTTP requests (via Faraday, Net::HTTP).                                                                                                                                                                                  
  ┌──────────────────────┬──────────────┬────────────────────────────┬─────────────────────────┐                                                                                                                                        
  │        Metric        │     Type     │           Source           │       Description       │                                                                                                                                        
  ├──────────────────────┼──────────────┼────────────────────────────┼─────────────────────────┤                                                                                                                                        
  │ http.client.requests │ counter      │ Instrumentation middleware │ Outgoing requests count │                                                                                                                                        
  ├──────────────────────┼──────────────┼────────────────────────────┼─────────────────────────┤                                                                                                                                        
  │ http.client.duration │ distribution │ request.faraday event      │ Request duration in ms  │                                                                                                                                        
  ├──────────────────────┼──────────────┼────────────────────────────┼─────────────────────────┤                                                                                                                                        
  │ http.client.errors   │ counter      │ Error tracking             │ Failed requests         │                                                                                                                                        
  └──────────────────────┴──────────────┴────────────────────────────┴─────────────────────────┘                                                                                                                                        
  Attributes: host, method, status_code                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
  Sources: https://tlatsas.github.io/2021/02/26/faraday-requests-instrumentation/, https://opentelemetry.io/docs/languages/ruby/libraries/                                                                                              
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  12. Redis Connection Pool Metrics                                                                                                                                                                                                     
                                                                                                                                                                                                                                        
  For applications using Redis with connection pooling.                                                                                                                                                                                 
  ┌──────────────────────┬───────┬────────────────┬───────────────────────┐                                                                                                                                                             
  │        Metric        │ Type  │     Source     │      Description      │                                                                                                                                                             
  ├──────────────────────┼───────┼────────────────┼───────────────────────┤                                                                                                                                                             
  │ redis.pool.size      │ gauge │ pool.size      │ Maximum pool size     │                                                                                                                                                             
  ├──────────────────────┼───────┼────────────────┼───────────────────────┤                                                                                                                                                             
  │ redis.pool.available │ gauge │ pool.available │ Available connections │                                                                                                                                                             
  ├──────────────────────┼───────┼────────────────┼───────────────────────┤                                                                                                                                                             
  │ redis.pool.idle      │ gauge │ pool.idle      │ Idle connections      │                                                                                                                                                             
  └──────────────────────┴───────┴────────────────┴───────────────────────┘                                                                                                                                                             
  Sources: https://github.com/mperham/connection_pool                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  Summary by Priority                                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  High Value (Recommended for Initial Implementation)                                                                                                                                                                                   
                                                                                                                                                                                                                                        
  1. Ruby Runtime - GC count, heap slots, RSS memory                                                                                                                                                                                    
  2. Puma - Pool capacity, busy threads, requests count                                                                                                                                                                                 
  3. DB Connection Pool - Busy, waiting, dead connections                                                                                                                                                                               
  4. Sidekiq - Queue latency, size, processed/failed counts                                                                                                                                                                             
                                                                                                                                                                                                                                        
  Medium Value (Second Phase)                                                                                                                                                                                                           
                                                                                                                                                                                                                                        
  5. Rails Cache - Hit/miss rates                                                                                                                                                                                                       
  6. HTTP Client - Request counts, duration distribution                                                                                                                                                                                
  7. Other Job Queues - Solid Queue, Delayed Job, Resque, GoodJob                                                                                                                                                                       
                                                                                                                                                                                                                                        
  Lower Priority (Future Consideration)                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
  8. ActionCable - Connection counts                                                                                                                                                                                                    
  9. Redis Pool - Connection availability                                                                                                                                                                                               
                                                                                                                                                                                                                                        
  ---                                                                                                                                                                                                                                   
  These metrics provide lightweight runtime health visibility without overlapping with spans/traces. They can be collected on a periodic basis (e.g., every 10-60 seconds) or on specific events, depending on the metric type.         
                                                                                                                                                                                                                                        
✻ Cogitated for 4m 0s                                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
> add this as a comment on the original issue                                                                                                                                                                                           
                                                                                                                                                                                                                                        
⏺ Bash(gh issue comment 2808 --repo getsentry/sentry-ruby --body "# Auto-Collected Metrics for Ruby Ecosystem…)                                                                                                                         
  ⎿  https://github.com/getsentry/sentry-ruby/issues/2808#issuecomment-3768679021                                                                                                                                                       
                                                                                                                                                                                                                                        
⏺ Done. The research findings have been added as a comment on the issue: https://github.com/getsentry/sentry-ruby/issues/2808#issuecomment-3768679021                                                                                   
                                                                                                                                                                                                                                        