#date: 2023-03-30T16:45:31Z
#url: https://api.github.com/gists/67833d37f95f5f87401e39c12e969db7
#owner: https://api.github.com/users/alex000kim

import pytest

from detect_reminder import is_reminder_request

# test examples were generated by asking ChatGPT the following:
# "Provide multiple examples a user can ask a chatbot to set a reminder"
@pytest.mark.parametrize("user_input,expected_result", [
    ("Can you remind me to call John at 5 PM today?", True),
    ("Please set a reminder for my dentist appointment on October 21st at 2 PM.", True),
    ("Schedule a reminder for me to buy groceries tomorrow at 10 AM.", True),
    ("Help me remember to take my medication at 8 AM every day.", True),
    ("I need to be reminded to pick up my dry cleaning on Friday afternoon.", True),
    ("Reminder: Feed the cat at 7 PM every evening.", True),
    ("Kindly notify me to pay the bills on the 1st of every month.", True),
    ("Don't let me forget to send an email to Sarah at noon.", True),
    ("Set an alert for me to water the plants every three days at 9 AM.", True),
    ("Please help me remember to book tickets for the concert on Saturday at 11 AM.", True),
    ("What's the weather like today?", False),
    ("How to cook pasta?", False),
    ("Find the nearest restaurant.", False),
    ("Who won the soccer match yesterday?", False),
    ("Suggest a good movie to watch this weekend.", False),
    ("When is daylight saving time starting?", False),
    ("Tell me a joke.", False),
    ("Could you recommend a book?", False),
    ("What's the capital of Germany?", False),
    ("Translate 'hello' to Spanish.", False),
])
def test_is_reminder_request(user_input, expected_result):
    result = is_reminder_request(user_input)
    assert result == expected_result, f"Failure for input: '{user_input}'"

    
# $ pytest test_reminder.py 
# =================================================== test session starts ====================================================
# platform darwin -- Python 3.9.10, pytest-7.2.2, pluggy-1.0.0
# rootdir: /Users/akim/Desktop/gh/my_repos/slack-gpt-bot
# collected 20 items                                                                                                         

# test_reminder.py ....................                                                                                [100%]

# =================================================== 20 passed in 23.56s ====================================================