#date: 2022-03-01T16:49:29Z
#url: https://api.github.com/gists/574bf87125fe6018197490d40ca5125a
#owner: https://api.github.com/users/nnkennard

text = "CHAPTER I TREATS OF THE PLACE WHERE OLIVER TWIST WAS BORN AND OF THE CIRCUMSTANCES ATTENDING HIS BIRTH Among other public buildings in a certain town , which for many reasons it will be prudent to refrain from mentioning , and to which I will assign no fictitious name , there is one anciently common to most towns , great or small : to wit , a workhouse ; and in this workhouse was born ; on a day and date which I need not trouble myself to repeat , inasmuch as it can be of no possible consequence to the reader , in this stage of the business at all events ; the item of mortality whose name is prefixed to the head of this chapter .\n\nFor a long time after it was ushered into this world of sorrow and trouble , by the parish surgeon , it remained a matter of considerable doubt whether the child would survive to bear any name at all ; in which case it is somewhat more than probable that these memoirs would never have appeared ; or , if they had , that being comprised within a couple of pages , they would have possessed the inestimable merit of being the most concise and faithful specimen of biography , extant in the literature of any age or country .\n\nAlthough I am not disposed to maintain that the being born in a workhouse , is in itself the most fortunate and enviable circumstance that can possibly befall a human being , I do mean to say that in this particular instance , it was the best thing for Oliver Twist that could by possibility have occurred ."

import stanza
STANZA_PIPELINE = stanza.Pipeline('en',
                                  processors='tokenize,lemma,pos,mwt,constituency',
                                  tokenize_pretokenized=True,
                                  tokenize_no_ssplit=True)
stanza.download('en')

doc = STANZA_PIPELINE(text)
for sentence in doc.sentences:
    print(" ".join([token.text for token in sentence.tokens]))
    print(sentence.constituency)
    print()


"""Output:
CHAPTER I TREATS OF THE PLACE WHERE OLIVER TWIST WAS BORN AND OF THE CIRCUMSTANCES ATTENDING HIS BIRTH Among other public buildings in a certain town , which for many reasons it will be prudent to refrain from mentioning , and to which I will assign no fictitious name , there is one anciently common to most towns , great or small : to wit , a workhouse ; and in this workhouse was born ; on a day and date which I need not trouble myself to repeat , inasmuch as it can be of no possible consequence to the reader , in this stage of the business at all events ; the item of mortality whose name is prefixed to the head of this chapter .
(ROOT (S (SBAR (IN Although) (S (NP (PRP I)) (VP (VBP am) (RB not) (VP (VBN disposed) (S (VP (TO to) (VP (VB maintain) (SBAR (IN that) (S (NP (DT the)) (VP (VBG being) (VP (VBN born) (PP (IN in) (NP (DT a) (NN workhouse)))))))))))))) (, ,) (VP (VBZ is) (PP (IN in) (NP (PRP itself))) (NP (NP (DT the) (ADJP (RBS most) (JJ fortunate) (CC and) (JJ enviable)) (NN circumstance)) (SBAR (WHNP (WDT that)) (S (VP (MD can) (ADVP (RB possibly)) (VP (VB befall) (NP (DT a) (JJ human) (NN being)))))))) (, ,) (NP (PRP I)) (VP (VBP do) (VP (VB mean) (S (VP (TO to) (VP (VB say) (SBAR (IN that) (S (PP (IN in) (NP (DT this) (JJ particular) (NN instance))) (, ,) (NP (NP (PRP it))) (VP (VBD was) (NP (NP (NP (DT the) (JJS best) (NN thing)) (PP (IN for) (NP (NNP Oliver) (NNP Twist)))) (SBAR (WHNP (WDT that)) (S (VP (MD could) (PP (IN by) (NP (NN possibility))) (VP (VB have) (VP (VBN occurred))))))))))))))) (. .)))

For a long time after it was ushered into this world of sorrow and trouble , by the parish surgeon , it remained a matter of considerable doubt whether the child would survive to bear any name at all ; in which case it is somewhat more than probable that these memoirs would never have appeared ; or , if they had , that being comprised within a couple of pages , they would have possessed the inestimable merit of being the most concise and faithful specimen of biography , extant in the literature of any age or country .
(ROOT (S (S (PP (IN For) (NP (NP (DT a) (JJ long) (NN time)) (SBAR (IN after) (S (NP (PRP it)) (VP (VBD was) (VP (VBN ushered) (PP (IN into) (NP (NP (DT this) (NN world)) (PP (IN of) (NP (NN sorrow) (CC and) (NN trouble))))))))))) (, ,) (PP (IN by) (NP (DT the) (NN parish) (NN surgeon))) (, ,) (NP (NP (PRP it))) (VP (VBD remained) (NP (NP (DT a) (NN matter)) (PP (IN of) (NP (JJ considerable) (NN doubt)))) (SBAR (IN whether) (S (NP (DT the) (NN child)) (VP (MD would) (VP (VB survive) (S (VP (TO to) (VP (VB bear) (NP (DT any) (NN name)) (ADVP (IN at) (DT all))))))))))) (: ;) (S (SBAR (WHPP (IN in) (WHNP (WDT which) (NN case))) (S (NP (NP (PRP it))) (VP (VBZ is) (ADVP (RB somewhat)) (ADJP (ADVP (JJR more)) (IN than) (JJ probable)) (SBAR (IN that) (S (NP (DT these) (NNS memoirs)) (VP (MD would) (ADVP (RB never)) (VP (VB have) (VP (VBN appeared))))))))) (: ;) (CC or) (, ,) (SBAR (IN if) (S (NP (PRP they)) (VP (VBD had)))) (, ,) (SBAR (IN that) (S (VP (VBG being) (VP (VBN comprised) (PP (IN within) (NP (NP (DT a) (NN couple)) (PP (IN of) (NP (NNS pages))))))))) (, ,) (NP (PRP they)) (VP (MD would) (VP (VB have) (VP (VBN possessed) (NP (NP (DT the) (JJ inestimable) (NN merit)) (PP (IN of) (S (VP (VBG being) (NP (NP (NP (DT the) (ADJP (RBS most) (JJ concise) (CC and) (JJ faithful)) (NN specimen)) (PP (IN of) (NP (NN biography)))) (, ,) (ADJP (JJ extant) (PP (IN in) (NP (NP (DT the) (NN literature)) (PP (IN of) (NP (DT any) (NN age) (CC or) (NN country))))))))))))))) (. .)))

Although I am not disposed to maintain that the being born in a workhouse , is in itself the most fortunate and enviable circumstance that can possibly befall a human being , I do mean to say that in this particular instance , it was the best thing for Oliver Twist that could by possibility have occurred .
(ROOT (S (S (NP (NP (NN CHAPTER)) (SBAR (S (NP (PRP I)) (VP (VBZ TREATS) (PP (IN OF) (NP (NP (DT THE) (NN PLACE)) (SBAR (WHADVP (WRB WHERE)) (S (NP (NNP OLIVER) (NNP TWIST)) (VP (VBD WAS) (NP (NP (ADJP (VBN BORN) (CC AND) (IN OF) (DT THE)) (NNS CIRCUMSTANCES)) (VP (VBG ATTENDING) (NP (PRP$ HIS) (NN BIRTH)) (PP (IN Among) (NP (JJ other) (JJ public) (NNS buildings))) (PP (IN in) (NP (NP (DT a) (JJ certain) (NN town)) (, ,) (SBAR (SBAR (WHNP (WDT which)) (S (PP (IN for) (NP (JJ many) (NNS reasons))) (NP (PRP it)) (VP (MD will) (VP (VB be) (ADJP (JJ prudent) (S (VP (TO to) (VP (VB refrain) (PP (IN from) (NP (VBG mentioning))))))))))) (, ,) (CC and) (SBAR (WHPP (IN to) (WHNP (WDT which))) (S (NP (PRP I)) (VP (MD will) (VP (VB assign) (NP (DT no) (JJ fictitious) (NN name)))))))))))))))))))) (, ,) (NP (EX there)) (VP (VBZ is) (SBAR (S (NP (NP (CD one)) (ADJP (ADVP (RB anciently)) (JJ common) (PP (IN to) (NP (NP (JJS most) (NNS towns)) (, ,) (NP (ADJP (ADJP (JJ great) (CC or) (JJ small)) (: :) (S (VP (TO to) (VP (VB wit)))))) (, ,) (NP (DT a) (NN workhouse)) (, ;) (CC and) (PP (IN in) (NP (DT this) (NN workhouse))))))) (VP (VBD was) (VP (VBN born))))))) (, ;) (S (PP (IN on) (NP (NP (DT a) (NN day) (CC and) (NN date)) (SBAR (WHNP (WDT which)) (S (NP (PRP I)) (VP (VBP need) (RB not) (VP (VB trouble) (NP (PRP myself)) (S (VP (TO to) (VP (VB repeat)))))))))) (, ,) (ADVP (RB inasmuch)) (SBAR (IN as) (S (NP (PRP it)) (VP (MD can) (VP (VB be) (PP (IN of) (NP (NP (DT no) (JJ possible) (NN consequence)) (PP (IN to) (NP (DT the) (NN reader))))) (, ,) (PP (IN in) (NP (NP (DT this) (NN stage)) (PP (IN of) (NP (DT the) (NN business))) (PP (IN at) (NP (DT all) (NNS events)))))))))) (, ;) (S (NP (NP (DT the) (NN item)) (PP (IN of) (NP (NP (NN mortality)) (SBAR (WHNP (WP$ whose) (NN name)) (S (VP (VBZ is) (VP (VBN prefixed) (PP (IN to) (NP (NP (DT the) (NN head)) (PP (IN of) (NP (DT this) (NN chapter)))))))))))) (. .))))
"""