#date: 2022-06-08T17:01:05Z
#url: https://api.github.com/gists/94ae911cfefed1781dfa5cbd4f2c3826
#owner: https://api.github.com/users/cpdean

[No Name]                                                                                                                                                                                                                                                                                                                                      0,0-1          All
  1        startup: 147.7                                                                                                                                                                                                                                                                                                                                        
  2 event                  time percent plot                                                                                                                                                                                                                                                                                                                     
  3 init.vim              53.67   36.33 ██████████████████████████                                                                                                                                                                                                                                                                                               
  4 backup.init.vim       53.52   36.23 █████████████████████████▉                                                                                                                                                                                                                                                                                               
  5 loading rtp plugins   17.77   12.03 ████████▋                                                                                                                                                                                                                                                                                                                
  6 NERD_tree.vim         13.09    8.86 ██████▍                                                                                                                                                                                                                                                                                                                  
  7 syntastic.vim         10.99    7.44 █████▍                                                                                                                                                                                                                                                                                                                   
  8 reading ShaDa          9.92    6.72 ████▊                                                                                                                                                                                                                                                                                                                    
  9 filetype.vim           9.35    6.33 ████▌                                                                                                                                                                                                                                                                                                                    
 10 gruvbox.vim            6.00    4.06 ██▉                                                                                                                                                                                                                                                                                                                      
 11 done waiting for UI    5.84    3.95 ██▉                                                                                                                                                                                                                                                                                                                      
 12 parsing arguments      4.09    2.77 ██                                                                                                                                                                                                                                                                                                                       
 13 matchit.vim            3.37    2.28 █▋                                                                                                                                                                                                                                                                                                                       
 14 loading after plugin   2.98    2.01 █▌                                                                                                                                                                                                                                                                                                                       
 15 rplugin.vim            2.33    1.58 █▏                                                                                                                                                                                                                                                                                                                       
 16 rplugin.vim            2.08    1.40 █                                                                                                                                                                                                                                                                                                                        
 17 opening buffers        2.06    1.39 █                                                                                                                                                                                                                                                                                                                        
 18 plug.vim               1.92    1.30 ▉                                                                                                                                                                                                                                                                                                                        
 19 go.vim                 1.81    1.22 ▉                                                                                                                                                                                                                                                                                                                        
 20 black.vim              1.80    1.22 ▉                                                                                                                                                                                                                                                                                                                        
 21 cmp.lua                1.61    1.09 ▊                                                                                                                                                                                                                                                                                                                        
 22 expanding arguments    1.49    1.01 ▊                                                                                                                                                                                                                                                                                                                        
 23 python3.vim            1.26    0.85 ▋                                                                                                                                                                                                                                                                                                                        
 24 fugitive.vim           1.10    0.74 ▌                                                                                                                                                                                                                                                                                                                        
 25 syntax.vim             1.07    0.72 ▌                                                                                                                                                                                                                                                                                                                        
 26 locale set             1.06    0.72 ▌                                                                                                                                                                                                                                                                                                                        
 27 jedi.vim               1.05    0.71 ▌                                                                                                                                                                                                                                                                                                                        
 28 vim_dadbod_completio   0.96    0.65 ▌                                                                                                                                                                                                                                                                                                                        
 29 fs_menu.vim            0.79    0.53 ▍                                                                                                                                                                                                                                                                                                                        
 30 fzf.vim                0.77    0.52 ▍                                                                                                                                                                                                                                                                                                                        
 31 fzf.vim                0.73    0.49 ▍                                                                                                                                                                                                                                                                                                                        
 32 util.vim               0.67    0.45 ▍                                                                                                                                                                                                                                                                                                                        
 33 syntax.vim             0.61    0.41 ▎                                                                                                                                                                                                                                                                                                                        
 34 notational_fzf.vim     0.61    0.41 ▎                                                                                                                                                                                                                                                                                                                        
 35 registry.vim           0.59    0.40 ▎                                                                                                                                                                                                                                                                                                                        
 36 inits 1                0.57    0.38 ▎                                                                                                                                                                                                                                                                                                                        
 37 BufEnter autocommand   0.54    0.36 ▎                                                                                                                                                                                                                                                                                                                        
 38 init highlight         0.48    0.33 ▎                                                                                                                                                                                                                                                                                                                        
 39 loclist.vim            0.48    0.33 ▎                                                                                                                                                                                                                                                                                                                        
 40 path.vim               0.48    0.32 ▎                                                                                                                                                                                                                                                                                                                        
 41 util.vim               0.41    0.28 ▎                                                                                                                                                                                                                                                                                                                        
 42 config.vim             0.41    0.28 ▎                                                                                                                                                                                                                                                                                                                        
 43 netrwPlugin.vim        0.41    0.27 ▎                                                                                                                                                                                                                                                                                                                        
 44 surround.vim           0.40    0.27 ▎                                                                                                                                                                                                                                                                                                                        
 45 ui_glue.vim            0.38    0.25 ▏                                                                                                                                                                                                                                                                                                                        
 46 vsnip.vim              0.37    0.25 ▏                                                                                                                                                                                                                                                                                                                        
 47 tree_dir_node.vim      0.36    0.24 ▏                                                                                                                                                                                                                                                                                                                        
 48 alchemist.vim          0.35    0.24 ▏           