#date: 2023-04-03T16:46:11Z
#url: https://api.github.com/gists/479e591dd9b2ec83bad612e11fbf04ba
#owner: https://api.github.com/users/leftl

export EDITOR='nvim'
export VISUAL=${EDITOR}
export PAGER='less'

export CLICOLOR=1

export LC_ALL=en_US.UTF-8

export ZDOTDIR=${HOME}/.config/zsh

# disable brew analytics
export HOMEBREW_NO_ANALYTICS=1
