#date: 2024-04-16T16:46:40Z
#url: https://api.github.com/gists/197f1fb160eda28812dad330a7b26cc6
#owner: https://api.github.com/users/nickmain

export PATH="$HOME/Developer/tools/bin:$PATH"

PS1='%1d 🔸 '
RPROMPT="%F{blue}%B%*%b%f"

alias la='ls -la'
alias now='date +"%s"'
alias ded="rm -rf ~/Library/Developer/Xcode/DerivedData;rm -rf ~/Library/Caches/org.swift.swiftpm"
alias ..='cd ..'
alias branch='git branch'
