#date: 2024-05-03T17:06:33Z
#url: https://api.github.com/gists/bcc2b4ad28d73c770b405a11ea0006fe
#owner: https://api.github.com/users/dm4

export FZF_COMPLETION_TRIGGER=',,'
_fzf_complete_j() {
  _fzf_complete --prompt="autojump> " -- "$@" < <(
    j -s | awk -F $'\t' '/^___/{exit} {print $2}' | tac
  )
}
_fzf_complete_j_post() {
  awk '{printf "\"%s\"", $0}'
}