#date: 2023-04-03T16:46:11Z
#url: https://api.github.com/gists/479e591dd9b2ec83bad612e11fbf04ba
#owner: https://api.github.com/users/leftl

#plugin manager & plugins
source ${ZDOTDIR}/init-znap.zsh

# History in cache directory:
export HISTSIZE=50000 # size of hist file
export SAVEHIST=20000 # size of hist held in memory
export HISTFILE=${ZDOTDIR}/history

# key bindings
# bindkey -e # enable all emacs bindings or just the few I use ontop of 
# default vi mode?
bindkey '^A' beginning-of-line
bindkey '^[[H' beginning-of-line
bindkey '^E' end-of-line
bindkey '^[[F' end-of-line
bindkey '^R' history-incremental-search-backward

# autoload -U colors; colors
# autoload -Uz url-quote-magic
# zle -N self-insert url-quote-magic

# if behavior isn't as expected, try the history-substring-search plugin instead
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search   # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data across sessions
setopt auto_cd
setopt correct_all

alias ls='ls -G'
alias ll='ls -lah'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias bup='brew update && brew upgrade'
alias vim='nvim'
