# This workflow will install Python seeker and run based on scheduler or events

name: seeker-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 17 * * 1-5"    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install seeker
      run: |      
        pip install -e .
    - name: run
      run: |
        GITHUB_TOKEN=${{ secrets.TOKEN }}
        env
        cd seeker
        seeker --help
